### PR TITLE
Get ready for release

### PR DESCRIPTION
**Pull request by davidanthoff**
I'd love to use this package, do you think you could register it soon? This PR is a bunch of smallish cleanup stuff. Could you also enable appveyor? Oh, and maybe also enable codecov?

### CODE REVIEW

**Comment by bkamins** [comment]
Thank you for the commit. It was not clear where the community wants to go with this package. But I think I will just make its first release and register it as is and it can be moved later to a more appropriate place.

**Comment by davidanthoff** [comment]
That would be great! I guess the repo could eventually be moved to https://github.com/JuliaArrays? But I agree, that could come later.

**Comment by bkamins** [comment]
I had to fix UUID and hopefully https://github.com/JuliaLang/METADATA.jl/pull/21494 will pass.

**Comment by davidanthoff** [comment]
Easiest solution: delete the Project.toml :)

**Comment by bkamins** [comment]
@davidanthoff The package is registered.

**Pull request merged**
